### ISSUE TITLE
Use revealation error event.js 85

### ISSUE THREAD

**Issue by VincentSim** [codemiller/revealation#4]
Here is my issue when I run : ```$ revealation http://mypresentation.com/```
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn casperjs ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by toddhalfpenny** [comment]
Same here... running v0.12.7

**Comment by katiejots** [comment]
I haven't been able to repro this - can you give more info about your system?

It looks like someone has recently written a tool that subsumes this one (https://github.com/astefanutti/decktape), and is hopefully more up-to-date and robust than my quick script - you could give that a try.
